name: Ong.ph
favicon: null
layout_spectrum: 0.24624
typography_spectrum: 0.24865
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050605'
    - '#FF394C'
    - '#FFFFFF'
    - '#B46E53'
    - '#774227'
  brandStrength: 0
  lightness: 0.8009648788720369
  saturation: 0.3125
  rhythmicContrast: 0.7338097207248211
purpose: []
