name: Ong.ph
favicon: null
layout_spectrum: 0.970031937584281
typography_spectrum: 0.39765939908102155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6988952953834087
  lightness: 0.8009648788720369
  saturation: 0.21653067227452993
  rhythmicContrast: 0.7338097207248211
purpose: []
